server:
  port: 7001
spring:
  application:
    name: eureka-server1
#Eureka配置
eureka:
  instance:
    hostname: eureka-server1  #Eureka服务端实例名称
  client:   #服务端配置
    register-with-eureka: false   #是否向Eureka注册自己
    fetch-registry: false   #为false则表示自己就是注册中心
    service-url:
      #单机：就关注自己
      #集群（关联）：关联别人,填别人的地址（如果两个应用在同一台上，居然必须配置host来区分。无语）
      defaultZone: http://eureka-server2:7002/eureka/

