server:
  port: 8001
mybatis:
  type-aliases-package: com.ljj.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept   #此应用在注册中心的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/    #注册中心地址
  instance:
    instance-id: dept提供者8001  #用来修改注册中心上此应用的默认描述信息

#引入actuator依赖后，配置info中的信息，即可在erueka点击描述后显示出来
info:
  name: 李炯炯
  company: 陕汽

